name: Publish production
on:
  push:
    branches:
      - production
  workflow_dispatch:
    
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: echo ${{ secrets.TEST_ENV }}
      - uses: actions/checkout@v2
        with:
          ref: production
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

